[app]
    env = "test"
    port = "8080"

[log]
    access = "/log/job.log"
    error  = "/log/job_error.log"
    closed = false

[db.main]
    driver = "mysql"
    dsn = [
        "report_rw:A#^n5pbq2+kcDZ9@tcp(rm-2ze80066x5od03dc5.mysql.rds.aliyuncs.com:3306)/common_service?charset=utf8&loc=Local",
    ]
    log = "/log/job_sql.log"

[[cache]]
    driver =  "redis"
    nodes = ["127.0.0.1:6379"]
    password = ""
    expire= 300
    flush=300
