[server]
    env = "dev"
    port = "8001"

[log]
    access = "/tmp/access.log"
    error  = "/tmp/melon.log"

[job]
    pool = 1000

[db.main]
    driver = "mysql"
    dsn = [
        "report_rw:A#^n5pbq2+kcDZ9@tcp(rm-2ze80066x5od03dc5co.mysql.rds.aliyuncs.com:3306)/pp_job?charset=utf8&loc=Local",
        # "root:123456@tcp(127.0.0.1:3306)/pp_job?charset=utf8&loc=Local",
    ]
    log = "/tmp/sql.log"

[[cache]]
    driver =  "redis"
    nodes = ["127.0.0.1:6379"]
    password = ""
    expire= 300
    flush=300