[server]
    env = "dev"
    port = "8010"

[log]
    access = "/tmp/access.log"
    error  = "/tmp/melon.log"

[job]
    pool = 1000

[db.main]
    driver = "mysql"
    dsn = [
        "root:123456@tcp(127.0.0.1:3306)/pp_job?charset=utf8&loc=Local",
        # "root:123456@tcp(127.0.0.1:3306)/pp_job?charset=utf8&loc=Local",
    ]
    log = "/tmp/sql.log"

[[cache]]
    driver =  "redis"
    nodes = ["127.0.0.1:6379"]
    password = ""
    expire= 300
    flush=300

[email]
    host = "smtp.sina.com"
    port = "25"
    user = ""
    password = ""
    from = ""

# 短信通知方式配置
[sms]
url = "http://xx.com/api/tools/send_sms"
# pool = 10

# 钉钉通知配置
[ding]
url = "https://oapi.dingtalk.com/robot/send?access_token=%s"
# pool = 10

# 微信通知方式配置
[wechat]
url = "http://xx.com/api/tools/send_wechat"
# pool = 10